### PR TITLE
adding to lindsaycarr's commit

### PR DESCRIPTION
**Pull request by jordansread**
@lindsaycarr merge if appropriate? Still missing descriptions

### CODE REVIEW

**Comment by lindsayplatt** [comment]
@jread-usgs so I merge this to my master and then we merge my PR, correct?

I have just finished up some more descriptions - do you have specific ones you are thinking of?

**Comment by jordansread** [comment]
No, I hadn't added any to the states. You can if you are up for it. Basically the blue dots are discharge sites, and the red dots are DO sites. 

For ecoregions, it is just one dot per site and they are colored relative to how many sites we have. 

Give me 10 more mins on the merge, I am working something more in

**Comment by jordansread** [comment]
ok, good to go @lindsaycarr but something seems whack w/ those leaflet tiles on my rendering. You seeing the same thing?

**Comment by lindsayplatt** [comment]
from the ecoregions map? this is what I see:

image

**Comment by jordansread** [comment]
nope, the states maps below it

**Comment by lindsayplatt** [comment]
ok, so I checked out your branch, but your changes don't show up. Normally, I would have to build and reload. However, there's only a "Build All" tool for this package and it errs out immediately

**Comment by jordansread** [comment]
this isn't a package, it is set up as a makefile. So don't try to build it. Instead source what you need to source

**Comment by jordansread** [comment]
none of the new code is in the Rmd though? you sure?

**Comment by lindsayplatt** [comment]
oh ok, I am not familiar with makefiles. I'm going to try branching one more time

**Pull request merged**
